alias gcl "git clone"
alias lock "caelestia shell lock lock"
alias sv "sudo -E nvim"
alias fm yazi
alias ranger yazi
alias almh "almh.py"
alias cp "cp -r"
alias ts "sudo -E timeshift-gtk"
alias sfm "sudo -E thunar"
alias mpdmusics "ncmpcpp -c ~/.ncmpcpp/config-art"
alias cn "cd ~/shizuru"
#alias ls "eza --long --header --icons --git --group-directories-first "
alias ls 'g -tb --tb-style=unicode --all --title --total-size --sort=size'
#alias ls "lsd"
alias l "ls -a"
alias lt "ls --tree"
alias gadd "git add ."
alias gcommit "git commit -m"
alias gpush "git push -u origin main"
alias ... "cd ../.."
alias .... "cd ../../.."
alias fuck "nh os switch"
alias fucku "nh os switch --update"
alias rollfuck "sudo nixos-rebuild switch --rollback --flake .#shizuru"
alias fuckgc 'nh clean all'
alias fuckdit "codium ~/shizuru/"
alias x "exit"
alias e "clear"
alias ff "fastfetch"
alias nf "nitch"
alias mf "microfetch"
alias fucknix "sudo nixos-rebuild switch --flake .#shizuru"
alias cd "z"
alias zj "zellij"
alias tm "tmux"
alias ffnew "ff --config ~/.config/fastfetch/new.jsonc"
alias ffbochi "ff --config ~/.config/fastfetch/13.jsonc"
alias ffr "ff --config ~/.config/fastfetch/10.jsonc"
alias hey "hix-maintain"
alias foot-ff "fastfetch --raw ~/.config/fastfetch/out.sixel --logo-width 40 --logo-height 20"
alias listgen "sudo nix-env -p /nix/var/nix/profiles/system --list-generations";
